apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:latest

      initContainers:
        - name: proxy
          image: memcached:alpine
          restartPolicy: Always
          args: ["-o", "proxy_config=routelib,proxy_arg=/etc/config.lua", "-vv"]
          ports:
            - containerPort: 11211
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/config.lua
              subPath: config.lua
          resources:
            limits:
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          livenessProbe:
            tcpSocket:
              port: 11211
          readinessProbe:
            tcpSocket:
              port: 11211
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  labels:
    app: app
data:
  config.lua: |
    pools{
      set_all = {
        { backends = { "memcached-0.memcached-headless.cache.svc.cluster.local:11211" } },
        { backends = { "memcached-1.memcached-headless.cache.svc.cluster.local:11211" } },
        { backends = { "memcached-2.memcached-headless.cache.svc.cluster.local:11211" } },
      },
    }

    routes{
      -- get command polls all servers and returns first response
      cmap = {
        get = route_allfastest{
          children = "set_all",
          miss = true, -- failover on miss
        },
      },
      -- by default, send commands everywhere. ie; touch/set/delete
      default = route_allsync{
        children = "set_all",
      },
    }