apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx:latest
          
      initContainers:
        - name: cache-proxy
          image: memcached:alpine
          restartPolicy: Always
          args: ["-o", "proxy_config=routelib,proxy_arg=/etc/config.lua", "-vv"]
          ports:
            - containerPort: 11211
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/config.lua
              subPath: config.lua
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 150m
          livenessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5

        - name: cache
          image: memcached:alpine
          restartPolicy: Always
          args: ["-m", "64", "-p", "11212", "-vv"]
          ports:
            - containerPort: 11212
          resources:
            requests:
              memory: 96Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
          livenessProbe:
            tcpSocket:
              port: 11212
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 11212
            initialDelaySeconds: 5
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  labels:
    app: app
data:
  config.lua: |
    local_zone("sidecar")

    pools{
      set_all = {
        sidecar = {
          backends = {
            "127.0.0.1:11212",
          },
        },
        cluster = {
          backends = {
            "cache-0.cache-headless.cache.svc.cluster.local:11211",
            "cache-1.cache-headless.cache.svc.cluster.local:11211",
            "cache-2.cache-headless.cache.svc.cluster.local:11211",
          },
        },
      },
    }

    routes{
      cmap = {
        -- zoned pool set given, so the pool specified in local_zone is tried first
        get = route_failover{
          children = "set_all",
          miss = true, -- failover on miss
        },
      },

      default = route_allsync{ children = "set_all" }    
    }