direction: right

Node 0 {
    App Pod.Proxy Sidecar -> cache-0
    App Pod {
        App -> Proxy Sidecar
        Proxy Sidecar -> Local Cache Sidecar
    }
}

Node 0.App Pod.Proxy Sidecar -> Node 1.cache-1