direction: right

Node 0 {
    App Pod.Sidecar Proxy -> cache-0
    App Pod {
        App -> Sidecar Proxy
        Sidecar Proxy -> Local Cache Sidecar
    }
}

Node 0.App Pod.Sidecar Proxy -> Node 1.cache-1